# -*- coding: utf-8 -*-
"""dataframe.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mgz0Dp0OUAICf-SB-VNLAVtXcEn_2MA4
"""

import pandas as pd
import random

def generate_clothing_warehouse_data(num_records=50):
    # Define ranges and categories
    months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    risk_levels = ['Low', 'Medium', 'High']
    sentiments = ['Positive', 'Neutral', 'Negative']
    data = []

    for _ in range(num_records):
        month = random.choice(months)
        warehouse_capacity = random.randint(5000, 20000)  # Capacity in units
        monthly_incoming = random.randint(1000, warehouse_capacity)  # Stock coming in
        monthly_outgoing = random.randint(1000, warehouse_capacity)  # Stock going out
        risk_analysis = random.choice(risk_levels)
        sentiment = random.choice(sentiments)

        data.append({
            'Month': month,
            'Warehouse Capacity': warehouse_capacity,
            'Monthly Incoming': monthly_incoming,
            'Monthly Outgoing': monthly_outgoing,
            'Risk Analysis': risk_analysis,
            'Sentiment': sentiment
        })

    # Convert data to a DataFrame
    df = pd.DataFrame(data)
    return df

# Generate dataset with 100 records
clothing_data = generate_clothing_warehouse_data(num_records=100)

# Save dataset to CSV
file_path = "clothing_warehouse_data.csv"
clothing_data.to_csv(file_path, index=False)
print(f"Dataset saved to '{file_path}'")

# Display first few rows of the dataset
print("\nSample Data:")
print(clothing_data.head())